Refactor fprettify and clang-format style checks to scripts to make use of it for local formatting (#42)
* Moving fprettify code to a separate script to make it more flexible

* Adding a script for clang-format

* fix typo

diff --git a/azure/azure_style.yaml b/azure/azure_style.yaml
--- a/azure/azure_style.yaml
+++ b/azure/azure_style.yaml
@@ -128,12 +128,14 @@ jobs:
 
           cd ${{ parameters.REPO_NAME }}
 
-          # if no local file is found in the repository, copy over the global .clang-format config file
-          if [[ ! -f ".clang-format" ]]; then
-            cp ../.github/.clang-format . || exit 1
+          # Check if we can access script, if not exit
+          if [[ ! -f ../.github/azure/clang-format.sh ]]; then
+            echo "clang-format.sh not found. Exiting."
+            exit 1
           fi
 
-          find . -iname '*.h' -o -iname '*.hpp' -o -iname '*.c' -o -iname '*.cpp' | xargs clang-format --verbose --dry-run --Werror -style=file
+          # Run the formatting
+          bash ../.github/azure/clang-format.sh --dry-run || exit $?
 
   - job: fprettify
     pool:
@@ -149,26 +151,17 @@ jobs:
       - script: |
           cd ${{ parameters.REPO_NAME }}
 
-          # If there is no local config file, copy over the global config file
-          if [[ ! -f ".fprettify.rc" ]]; then
-            cp ../.github/.fprettify.rc .
+          # Check if we can access script, if not exit
+          if [[ ! -f ../.github/azure/fprettify.sh ]]; then
+            echo "fprettify.sh not found. Exiting."
+            exit 1
           fi
 
           # Install fprettify
           pip install fprettify==0.3.7
 
-          # Run fprettify on non-differentiated Fortran 90 source files
-          find . -type f -iname '*.f90' ! -iname '*_b.f90' ! -iname '*_d.f90' -print0 | while read -d $'\0' file
-          do
-            echo Checking $file
-            fprettify $file
-
-            # Check if this file changed and print a message if it did
-            git diff --summary --exit-code $file
-            if [ $? -ne 0 ]; then
-              echo $file needs to be formatted
-            fi
-          done
+          # Run the formatting
+          bash ../.github/azure/fprettify.sh || exit $?
 
           # Exit with an error if any of the tracked files changed
           git diff --summary --exit-code
